### ISSUE TITLE
Add mountain_pass=yes name and altitude to the card

### ISSUE THREAD

**Issue by brunetton** [der-stefan/OpenTopoMap#140] opened 2017-12-31 10:06 UTC
Hi, 

First of all, I've to say that I use OpenTopo for a very long time, and I'm **very** enthusiastic about this project ! Great work, and thanks to everybody !

But I miss some very little details sometimes; as mountain pass markers. For example, here :

https://opentopomap.org/#map=17/44.24905/6.37060

If we compare to standard OSM rendering :

https://www.openstreetmap.org/#map=17/44.24905/6.37060

On the OSM rendering, we see the information: "Col du Labouret - 1240m". This is an important marker, as it correponds to real road signs on the road.

Do you see any problem adding this ?

Thanks a lot !

**Comment by max-dn** [comment] 2017-12-31 11:23
mountain_pass=yes is not rendered, but natural=saddle is. That's why you see the [icon and label in Zoom 14](https://opentopomap.org/#map=14/44.24452/6.38091). 
We have an other problem... we loose too many labels while zooming in. The label of the Col du Labouret should be visible in Zoom 14-17 like the [Col de Maure](https://opentopomap.org/#map=16/44.31854/6.40274). But it is not and I don't know, why this label is suppressed.. Same here: We have two passes [next to Pic des Tetes](https://opentopomap.org/#map=14/44.29993/6.46902), one looses it's icon in Zoom 14, the other one looses its label in Zoom 15-17.

**Comment by der-stefan** [comment] 2017-12-31 17:16
@brunetton: Thanks for reporting. The issue is now fixed. The label offset (dy) was not enough and the label was not placed since it overlapped with the saddle icon.
@max-dn: On the map it would like nice, if saddles on streets would have the same direction of the street. It could be that a street doesn't cross the saddle in 90 degree. What do you think?

**Comment by max-dn** [comment] 2017-12-31 17:53
In a ideal world the icon is allready correct ;) The DEM is correct, the constructor of the road took the lowest way over the ridge and  the icon is placed at the right position. In our world mostly the DEM is incorrect, the lowest place is a wet meadow forcing the constructor going some meters uphill and the icon and the street sign is placed at the parking place with the best photo point.
In most cases streets don't cross saddles in 90°, but in [some of them do](https://opentopomap.org/#map=16/44.98820/6.86921). For highway=primary it's not easy to find an example but at least for highway=path I find a lot of [ways along the ridge crossing some saddles](https://opentopomap.org/#map=15/47.43632/10.86194) or going up[ from a valley to saddle and then following the ridge](https://opentopomap.org/#map=17/47.46201/11.41024).
I think a rule like "saddle directions are following the next street" will produce more errors than we have now.

**Comment by brunetton** [comment] 2018-01-01 00:31
Thanks for this fix that close the problem I mentioned :-) A new year that begin well ;-)
Indeed @max-dn, there is a label problem with [col des têtes](https://www.openstreetmap.org/node/2412792221) labels that appears and disappear depending on the zoom level (visibles in 14, dissappear in 15 and more), but this isn't exactly the topic of this bug. Maybe there is another bug for this problem? 

Anyway, thanks to both of you and happy new mapping year!

**Comment by der-stefan** [comment] 2018-01-01 10:40
@brunetton: Just wait some days for the server to render the old tiles.
@max-dn: You are right, we should prefer the direction calculated from the DEM. By the way: The old TK50 even had no symbol for passes: [Achenpaß in TK50](https://geoportal.bayern.de/bayernatlas/?lang=de&topic=zeitr&bgLayer=atkis&time=2008&layers=zeitreihe_tk&layers_timestamp=20081231&X=5274906.33&Y=4472909.55&zoom=9).

**Closed by der-stefan** 2018-01-01 10:40 UTC
